{
 "title": "LLMOps Platform Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "type": "add-library-panel", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Prometheus Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Services Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}